# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Com.Test.AbhinavSharma.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/Com.Test.AbhinavSharma.csproj'
    testRunTitle: 'Com.Test.AbhinavSharma Test Execution Report'
